### ISSUE TITLE
Link issues in Serial.readString()

### ISSUE THREAD

**Issue by CommandMC** [arduino/reference-en#735] opened 2020-04-30 13:57 UTC
In the entry for [Serial.readString()](https://www.arduino.cc/reference/en/language/functions/communication/serial/readstring), links to other parts of the Reference redirect to the wrong page.
For example, the link to the "Serial main page" redirects to www.arduino.cc/reference/en/language/functions/serial.
The correct site would be www.arduino.cc/reference/en/language/functions/communication/serial/settimeout

**Comment by per1234** [comment] 2020-04-30 23:49
Thanks for reporting this @CommandMC. The issue is explained here:
https://github.com/arduino/reference-en/issues/729#issuecomment-619938197

Since we already have a report about this bug, and there is nothing that can be done to fix from this repository, I'll go ahead and close this issue.

**Closed by per1234** 2020-04-30 23:49 UTC
