### ISSUE TITLE
Suggestion: Add ternary operator explanation to if/then/else reference pages

### ISSUE THREAD

**Issue by cbfunky** [arduino/reference-en#599] opened 2019-05-20 13:34 UTC
I know there has already been [this closed proposal](https://github.com/arduino/reference-en/issues/519), but I thought I should mention it again because of the following:

I'm new to Arduino and haven't programmed in a very long time. I use the Arduino reference extensively. I work a lot with example code and when I don't understand something I have to look it up. The problem (and this has been mentioned as well in the above link) is that the ternary operators are impossible to look up unless you already know what it is. 

In my case, I had a vague feeling it was related to if/then/else, but reading the reference pages didn't shed any light on this. I only found an explanation after lengthy research and _only_ because I kind of knew what I was looking for.

I totally understand @per1234 's thoughts on the original issue, both pro and con, and I agree that this is not something a beginner would use themselves. But as a beginner myself I just wanted to bring it up again, as it _is_ used in example code a lot and finding information about it is hard. 

On behalf of all noobs, I would thank you for considering it :)

**Comment by per1234** [comment] 2019-05-20 19:04
That proposal is not closed and my views on the subject have changed a bit due to me receiving new information since the time I wrote it. I don't think we need two issue reports on this topic so I'm going to close this as a duplicate of https://github.com/arduino/reference-en/issues/519. I'll comment on https://github.com/arduino/reference-en/issues/519 with an update on my views.

**Closed by per1234** 2019-05-20 19:04 UTC
Labels: duplicate
